kind: Service
apiVersion: v1
metadata:
    name: codingtch-api-service-svc
spec:
    type: NodePort
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
    selector:
        app: codingtch-api-service-svc
